### ISSUE TITLE
[MPI_WP2]: 2. IsoMemo skin IsoMemo app

### ISSUE THREAD

**Issue by arunge** [Pandora-IsoMemo/iso-app#69]
## Updates for Isomemo skin: higher level of data fetching

- [x] For the Isomemo app (https://github.com/Pandora-IsoMemo/iso-app), introduce a higher level of data fetching. 
  
  Currently a script is used to map data from across different databases into a single table stored in our servers (https://github.com/Pandora-IsoMemo/iso-app/tree/main/R).
This script is something that can be edited as databases are added/removed/modified. The script should be modified so that a new option of allows for the creation of different data maps (between original data sources and our repository). -> https://github.com/Pandora-IsoMemo/iso-data/issues/4
In terms of the IsoMemo skin interface there would be a selection option (above “Database selection”) to select a single data map. Once a map is selected the options for Categories and corresponding fields are automatically updated. In the new script one should be able to give a link to a pdf file describing the metadata of each map). This this change implies also that the following will have to be updated (see https://github.com/Pandora-IsoMemo/iso-data/tree/main/R):
  - Connection to cross-references citation
  - Saving queries (rename “Save data selection” as “Save query)
  - IsoMemo CRAN package (include access to metadata file)
  - Data fetching via URL

  Select categories or fields: buttons to select all/none (see figure below)

  ![image](https://user-images.githubusercontent.com/16759098/195053058-b3841fd1-e052-4037-a507-c5da5a757eef.png)

## New option in the IsoMemo skin to load pre-saved queries

- [ ] Add a new option in the IsoMemo skin to load pre-saved queries (these correspond to the options illustrated in the figure above). These will be stored in GitHub. A text file with fixed named/location (in GitHub) but editable will be used to list these queries or a directory will be read.
  - potentially new tasks: save both sql codes and graphics merge the tables into the
profiles, user can use the profiles and load them for the users
  - Button to visualize metadata file (mentioned above) for each data map

## Iso-data (https://github.com/Pandora-IsoMemo/iso-data/tree/main/R): Implementing a Bibtext Citation for database entries
- [ ] Options to be implemented using the Rcrossref package:
  - add a "bibtex" citation style column to the database, such that the app only needs to translate from one style into another style. The translation is only a string operation that should be much faster than loading references from DOI on the fly. -> https://github.com/Pandora-IsoMemo/iso-data/issues/3
  - implement the UI and logic to change the reference style -> https://github.com/Pandora-IsoMemo/iso-app/issues/14
 
##  Updates for Pandora skin (see below)

![image](https://user-images.githubusercontent.com/16759098/195053581-4c756995-fc41-4a96-8407-7eea7057af9b.png)

- [x] **Duplicate search:** Users would be able to select fields of interest for duplicate identification from the Pandora skin within the IsoMemo app (https://github.com/Pandora-IsoMemo/iso-app/tree/main/R). In terms of matching options the user may select an exact match or if a string in one cell is contained within another. If the search should be case sensitive or not and if spaces should be considered or not. In terms of display, the user may select to add a new column where duplicates are flagged or only to display the first or last duplicate.
Duplicate search within IsoMemo: similar to above for the IsoMemo skin (see text above). -> https://github.com/Pandora-IsoMemo/iso-app/issues/88

- [x] For Pandora skin, currently users have to manually select **longitude and latitude** fields (see figure above). This should remain possible. However, now when selecting a data resource, the app will check if there are fields named Longitude or Long and Latitude or Lat. If so, these are automatically assigned as latitude/longitude. -> #67

## Updates for Pandora & IsoMemo skin

- [x] #99
be quite big depending on text size (see example below). Introduce an option to make these
smaller by having the user setting a max number of characters to be displayed.

![image](https://user-images.githubusercontent.com/16759098/195053864-c51e967a-bcfd-41d6-a51f-00cc8a113ea3.png)

- [x] #133
Users can show/hide administrative names and/or borders for different map display options (see figure below).

![image](https://user-images.githubusercontent.com/16759098/195054309-a2e43c62-d268-4f52-a36a-e31887e05ad0.png)

- [ ] For the GUI option to set location of North Arrow/Scale by coordinate and to set their size

### Restructure (split up) scripts for modeling tabs: 
- see: https://github.com/Pandora-IsoMemo/iso-app/issues/126

- [ ] Clean code structure following the descriptions given at the following links:
  - https://github.com/Pandora-IsoMemo/iso-app/issues/27
  - https://github.com/Pandora-IsoMemo/iso-app/issues/30

  Currently, all options for one tab of one model, e.g. "AverageR" are in one script, e.g. [03-modelResults2D.R](https://github.com/Pandora-IsoMemo/iso-app/blob/main/R/03-modelResults2D.R). Since they are so many inputs now, some of the inputs do depend on andinteract with each other. This leads to several rerenderings of the map if one input is changed and app becomes very slow.

  Isolate inputs and move them into their own module preventing them to interact with inputs outside this module. Additionally, add an "Apply" button to trigger a new rendering of the map.

  Modularize/isolate the following groups of inputs:
  - model inputs (currently most of them on the left side, an apply button already exists)
  - map view inputs, e.g. map range/center/... (currently most of them in the middle, an apply button already exists)
  - map content inputs, e.g. estimation type (currently most of them on the right side at the top, no button yet)
  - map style inputs, e.g. "show scale/title/...", colou/shape/... of location marks (currently most of them on the right side at the bottom, no button yet)

  If the user changes an input that belongs to one module, all dependencies inside this module
will be set before the map is rendered again. This should significantly reduce the number of
renderings.

  Reuse the newly created modules for e.g. map view and map style in the other modeling tabs
like "TimeR". By this, reduce the current "copy-paste" amount of the code, which reduces the
risk for bugs, and the time to fix them.

  Additionally, use a [newer syntax for the shiny modules](https://shiny.rstudio.com/articles/modules.html) that enables to add [tests for the module server functions](https://shiny.rstudio.com/articles/server-function-testing.html). 
- [x] Use frames where needed and where possible. -> https://github.com/Pandora-IsoMemo/iso-app/issues/4

### Download/upload of model objects

- [ ] Down-/Upload of model objects: The IsoMemo app (https://github.com/Pandora-IsoMemo/iso-app) offers 5 different models that can be applied to uploaded data:
   (estimateMap(), estimateMap3D(), estimateMapSpread(), estimateMapKernel(),
estimateMap3DKernel())

  Develop interface to down/upload model objects such that only the related inputs and plots are updated when a model is uploaded. This must contain checks that prevent uploading a model object from a different model than that which is currently active. 

  -> https://github.com/Pandora-IsoMemo/iso-app/pull/128

  For more details, see also https://github.com/Pandora-IsoMemo/iso-app/issues/3

### Saved Maps tab

- [x] From https://github.com/Pandora-IsoMemo/iso-app/issues/20 Under the main menu currently named "Saved maps" create new numeric maps. If the user selects the option region-circle, one can select an option to create a numeric map for a certain radius around a certain selected location center. This is already implemented and works well. However, if a user selects the option region-square the options remain the same. This option should be renamed as region-rectangle. Here, the modelling options should be the upper left/lower right corners of the rectangle area to defined with respective lat/long inputs.
Implementation within: https://github.com/Pandora-IsoMemo/iso-app/issues/19

**Comment by arunge** [comment]
@isomemo the "[higher level of data fetching](https://github.com/Pandora-IsoMemo/iso-app/issues/102#issuecomment-1593335309)" was added to the iso-app beta. The next step regarding this is to 
- [ ] test the ETL with a new schema and new data source
- [ ] if necessary fix issues with the etl

Please feel free to provide the new sources.

**Comment by arunge** [comment]
Regarding the higher level of data fetching there is the new issue: https://github.com/Pandora-IsoMemo/iso-app/issues/177

[Left here](https://github.com/Pandora-IsoMemo/iso-app/issues/69#issue-1404326437) is

- [ ] the Bibtex part, and
- [ ] the presaved queries part

**Comment by arunge** [comment]
I am closing here. There are issues in respective repositories for the last open tasks.
